# Basic
title: Da xia 的技术博客
subtitle: 不积跬步，无以至千里.
welcome_message: 欢迎访问我的博客，这里主要记录我的工作和生活
description: 踏入iOS开发行列不久，暂居北京。
creator: <a href="http://zdaxia.com">@zdaxia</a>

url: "http://zdaxia.com"

permalink: /:year/:month/:title/

# Format
highlighter: plain
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# supported colors: blue, green,  purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 访问博客

# Navigation buttons in the front page.
nav:
    - {title: 关于, description: 了解更多关于我, url: '#'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    # disqus: vno-jekyll
    duoshuo: snail
    
# Social
social:
    # weibo: onevcat
    # github: onevcat
    # twitter: onevcat
    # gplus: 107108267983477358170
    mail: woshizhoudaixa@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
